import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  users,
  todos
}: {
  children: React.ReactNode
  users: React.ReactNode
  todos: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='py-24'>
          {children}
          {users}
          {todos}
        </main>
      </body>
    </html>
  )
}
